# Configuration file

# Microservices ports
ADD_MICROSERVICE_PORT = 5001
SUBTRACT_MICROSERVICE_PORT = 5002
MULTIPLY_MICROSERVICE_PORT = 5003
DIVIDE_MICROSERVICE_PORT = 5004

# Main application port
APP_PORT = 8000
