version: "3"
services:
  api:
    build:
      context: ./api/add
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db

  subtract_microservice:
    build:
      context: ./api/subtract
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - db

  multiply_microservice:
    build:
      context: ./api/multiply
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    depends_on:
      - db

  divide_microservice:
    build:
      context: ./api/divide
      dockerfile: Dockerfile
    ports:
      - "5003:5000"
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile_db
    volumes:
      - ./data:/app/data

  ux:
    build:
      context: ./ux
      dockerfile: Dockerfile_ux
    ports:
      - "80:80"

# Add any other services you have here.