# Use a lightweight web server image to serve the UI
FROM nginx:alpine

# Remove default Nginx configuration
RUN rm -rf /etc/nginx/conf.d/*

# Copy the custom Nginx configuration
COPY ux/nginx.conf /etc/nginx/conf.d/default.conf

# Copy the static files to the web server directory
COPY ux/ /usr/share/nginx/html/

# Expose port 80 for web server
EXPOSE 80

# Start the web server
CMD ["nginx", "-g", "daemon off;"]
