# Use an nginx base image
FROM nginx:alpine

# Remove the default nginx configuration
RUN rm -rf /etc/nginx/conf.d/*

# Copy the custom nginx configuration
COPY ./nginx.conf /etc/nginx/conf.d/

# Copy the UI files to the web server root
COPY ./* /usr/share/nginx/html/

# Expose the HTTP port
EXPOSE 80

# Start the nginx web server
CMD ["nginx", "-g", "daemon off;"]
