# Use a Python base image
FROM python:3.9

# Set the working directory
WORKDIR /app

# Install any other dependencies if required
# For example, if your project requires Flask:
# COPY db/requirements.txt /app/
# RUN pip install --no-cache-dir -r requirements.txt

# Copy the database setup script
COPY . /app/

# Expose the SQLite database file path as an environment variable
ENV SQLITE_DB_PATH /app/calculator.db

# Create the SQLite database file
RUN python setup_database.py

# Expose the database port (not needed for SQLite)
# EXPOSE 5432

# Start the database service (SQLite doesn't need a separate process)
# CMD ["command_to_start_db_server"]
